// Generated by: npm run set-defaults -- <export.json>
// Keys applied on first install (when localStorage is empty)

const DEFAULTS = {
  "quick-links": "[{\"label\":\"GitHub\",\"url\":\"https://github.com\",\"icon\":\"🐙\"},{\"label\":\"Gmail\",\"url\":\"https://mail.google.com\",\"icon\":\"✉️\"},{\"label\":\"YouTube\",\"url\":\"https://youtube.com\",\"icon\":\"▶️\"},{\"label\":\"Claude\",\"url\":\"https://claude.ai\",\"icon\":\"🤖\"}]",
  "shortcuts": "[{\"category\":\"Brave\",\"keys\":\"Ctrl+T\",\"description\":\"Nouvel onglet\"},{\"category\":\"Brave\",\"keys\":\"Ctrl+L\",\"description\":\"Focus barre URL\"},{\"category\":\"Brave\",\"keys\":\"Ctrl+Shift+N\",\"description\":\"Navigation privée\"},{\"category\":\"Brave\",\"keys\":\"Ctrl+Shift+J\",\"description\":\"Téléchargements\"},{\"category\":\"VS Code\",\"keys\":\"Ctrl+P\",\"description\":\"Ouvrir un fichier\"},{\"category\":\"VS Code\",\"keys\":\"Ctrl+Shift+P\",\"description\":\"Palette commandes\"},{\"category\":\"VS Code\",\"keys\":\"Ctrl+`\",\"description\":\"Terminal intégré\"},{\"category\":\"VS Code\",\"keys\":\"Ctrl+B\",\"description\":\"Panneau latéral\"},{\"category\":\"Système\",\"keys\":\"Win+D\",\"description\":\"Afficher le bureau\"},{\"category\":\"Système\",\"keys\":\"Win+V\",\"description\":\"Historique presse-papiers\"},{\"category\":\"Système\",\"keys\":\"Win+Shift+S\",\"description\":\"Capture d'écran\"}]",
  "background": "grid",
  "gs-layout-v": "8",
  "palette": "cyberpunk",
  "gs-layout-user-default": "[{\"x\":1,\"y\":0,\"w\":15,\"h\":42,\"id\":\"shortcuts\"},{\"x\":24,\"y\":0,\"w\":15,\"h\":7,\"id\":\"clock\"},{\"x\":40,\"y\":0,\"w\":48,\"h\":5,\"id\":\"search\"},{\"x\":88,\"y\":0,\"w\":12,\"h\":10,\"id\":\"weather\"},{\"x\":111,\"y\":0,\"w\":16,\"h\":18,\"id\":\"todo\"},{\"x\":40,\"y\":5,\"w\":48,\"h\":8,\"id\":\"quick-links\"},{\"x\":24,\"y\":8,\"w\":15,\"h\":10,\"id\":\"pomodoro\"},{\"x\":107,\"y\":31,\"w\":20,\"h\":24,\"id\":\"rss\"},{\"x\":24,\"y\":41,\"w\":40,\"h\":18,\"id\":\"notes\"}]",
  "gs-hidden-widgets": "[]",
}

export function applyDefaults() {
  if (!Object.keys(DEFAULTS).length) return
  Object.entries(DEFAULTS).forEach(([key, value]) => {
    if (localStorage.getItem(key) === null && value !== null) {
      localStorage.setItem(key, value)
    }
  })
}
